version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn install
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/OrderService-0.0.1-SNAPSHOT.jar
  discard-paths: yes